### ISSUE TITLE
Identifier 'expandRulesInclude' has already been declared

### ISSUE THREAD

**Issue by chrys-exaucet** [oklas/react-app-rewire-alias#22]
Hello @oklas,

I am facing this error while running my react tests with some aliased files.
 Is it related to your library? I saw related previous issues in this repo in vain. 

```
$ react-app-rewired test -- --config=jest.config.ts
C:\Users\project\node_modules\react-app-rewire-alias\src\aliasDangerous.js:30
function expandRulesInclude(rules, include) {
^

SyntaxError: Identifier 'expandRulesInclude' has already been declared
    at wrapSafe (internal/modules/cjs/loader.js:1172:16)
    at Module._compile (internal/modules/cjs/loader.js:1220:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Module.require (internal/modules/cjs/loader.js:1145:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (C:\Users\Utilisateur\Documents\gamma\gamma-ui\gamma-web-client\node_modules\react-app-rewire-alias\lib\aliasDangerous.js:1
:18)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

````

When I change aliasDangerous to alias, I face this other error:

```
module.exports.jest = aliasJest(aliasMap)
                      ^

TypeError: aliasJest is not a function
    at Object.<anonymous> (C:\Users\Utilisateur\Documents\gamma\gamma-ui\gamma-web-client\apps\administration-service\config-overrides.js:6:23)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Module.require (internal/modules/cjs/loader.js:1145:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (C:\Users\Utilisateur\Documents\gamma\gamma-ui\gamma-web-client\node_modules\react-app-rewired\config-overrides.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.



```

Here is my config.ovverrides

```js
const {aliasDangerous, aliasJest, configPaths} = require('react-app-rewire-alias/lib/aliasDangerous')

const aliasPaths = configPaths('./tsconfig.paths.json')

module.exports = aliasDangerous(aliasPaths)
module.exports.jest = aliasJest(aliasPaths)

```

**Comment by chrys-exaucet** [comment]
Moved to     "react-app-rewire-alias": "^1.0.1",

It's all good.
