### ISSUE TITLE
TypeError: aliasJest is not a function

### ISSUE THREAD

**Issue by chrys-exaucet** [oklas/react-app-rewire-alias#23]
Runing a react test - with typescript enabled - as stated in your example, I face this error:

```
module.exports.jest = aliasJest(aliasMap)
                      ^

TypeError: aliasJest is not a function
    at Object.<anonymous> (C:\Users\Utilisateur\Documents\gamma\gamma-ui\gamma-web-client\apps\administration-service\config-overrides.js:6:23)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Module.require (internal/modules/cjs/loader.js:1145:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (C:\Users\Utilisateur\Documents\gamma\gamma-ui\gamma-web-client\node_modules\react-app-rewired\config-overrides.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
```

 "react-app-rewire-alias": "^0.2.0",
    "react-app-rewired": "^2.1.8",
    "typescript": "^4.1.3",
  "react": "^17.0.1",
```

**Comment by chrys-exaucet** [comment]
Moved to     "react-app-rewire-alias": "^1.0.1".
Its all good.
