### ISSUE TITLE
Craco plugin + aliasDangerous

### ISSUE THREAD

**Issue by rkclark** [oklas/react-app-rewire-alias#25]
Hi there,

Thanks for maintaining this package! 🙇 

We use the craco plugin, but we also need to make use of "aliasDangerous" following the recent updates. Is that currently possible (couldn't find anything in the docs)?

Thanks!

**Comment by oklas** [comment]
Hi,

Thanks for interesting in this package. Search for `CracoAliasPlugin` in *diff-style* code snippet in  section [Outside of root](https://github.com/oklas/react-app-rewire-alias#outside-of-root)

Regards

**Comment by oklas** [comment]
Please

**Comment by rkclark** [comment]
Hey thanks for the quick reply.

So when we use the CracoAliasPlugin we don't import `alias`, so we can't replace with `aliasDangerous`.

We import/setup like this:

```
const { CracoAliasPlugin, configPaths } = require('react-app-rewire-alias');

const aliasConfigPath = path.resolve(__dirname, './jsconfig.paths.json');
```

And our craco config includes:

```
plugins: [
    {
      plugin: CracoAliasPlugin,
      options: { alias: configPaths(aliasConfigPath) },
    },
  ],
```

If we upgrade to latest react-app-rewire-alias then when we try to run our dev server we get the error below and the dev server fails to start:

```
alias 'application-lib' is outside of root - supported only by aliasDangerous
alias '@questions-global' is outside of root - supported only by aliasDangerous
alias '@questions-product' is outside of root - supported only by aliasDangerous
https://github.com/oklas/react-app-rewire-alias#outside-of-root
```

I tried changing the CracoAliasPlugin options to have "aliasDangerous":

```
  plugins: [
    {
      plugin: CracoAliasPlugin,
      options: { aliasDangerous: configPaths(aliasConfigPath) },
    },
  ],
```

But then we get this error from the dev server:

```
/Users/richardclark/ctm/motor.journeys/node_modules/react-app-rewire-alias/src/index.js:103
    throw Error('react-app-rewire-alias:configPaths: there is no config file found')
          ^

Error: react-app-rewire-alias:configPaths: there is no config file found
    at configPaths (/Users/richardclark/ctm/motor.journeys/node_modules/react-app-rewire-alias/src/index.js:103:11)
    at Object.overrideWebpackConfig (/Users/richardclark/ctm/motor.journeys/node_modules/react-app-rewire-alias/src/index.js:135:39)
    at overrideWebpack (/Users/richardclark/ctm/motor.journeys/node_modules/@craco/craco/lib/features/plugins.js:42:40)
    at /Users/richardclark/ctm/motor.journeys/node_modules/@craco/craco/lib/features/plugins.js:64:29
    at Array.forEach (<anonymous>)
    at applyWebpackConfigPlugins (/Users/richardclark/ctm/motor.journeys/node_modules/@craco/craco/lib/features/plugins.js:63:29)
    at mergeWebpackConfig (/Users/richardclark/ctm/motor.journeys/node_modules/@craco/craco/lib/features/webpack/merge-webpack-config.js:110:30)
    at overrideWebpackDev (/Users/richardclark/ctm/motor.journeys/node_modules/@craco/craco/lib/features/webpack/override.js:11:36)
    at /Users/richardclark/ctm/motor.journeys/node_modules/@craco/craco/scripts/start.js:27:5
```

Any ideas? 🙏 

Thanks

**Comment by oklas** [comment]
You need to import all using require with another path: 

```diff
- const { CracoAliasPlugin, configPaths } = require('react-app-rewire-alias');
+ const { CracoAliasPlugin, configPaths } = require('react-app-rewire-alias/lib/aliasDangerous');
```

I added additional notice in docs.

Let me know if any thoughts

**Comment by rkclark** [comment]
It works! Thank you very much 🙇

**Comment by AVAVT** [comment]
Hello, I'm having the same issue. Updating the import path seems to break the plugins:
```
const {
  CracoAliasPlugin,
  configPaths,
} = require("react-app-rewire-alias/lib/aliasDangerous");

const aliasMap = configPaths("./jsconfig.paths.json");

module.exports = {
  plugins: [
    {
      plugin: CracoAliasPlugin,
      options: { alias: aliasMap },
    },
  ],
};
```
Result in:
```
Error:
      react-app-rewire-alias:configPaths: array expected for paths, specify ./jsconfig.paths.json instead of D:\Administration\administration-ui\jsconfig.json for configPaths()
    at configPathsRaw (D:\Administration\administration-ui\node_modules\react-app-rewire-alias\src\index.js:110:11)
    at expandPluginsTsChecker (D:\Administration\administration-ui\node_modules\react-app-rewire-alias\src\aliasDangerous.js:81:21)
    at D:\Administration\administration-ui\node_modules\react-app-rewire-alias\src\aliasDangerous.js:126:5
    at Object.overrideWebpackConfig (D:\Administration\administration-ui\node_modules\react-app-rewire-alias\src\aliasDangerous.js:133:62)
    at overrideWebpack (D:\Administration\administration-ui\node_modules\@craco\craco\lib\features\plugins.js:42:40)
    at D:\Administration\administration-ui\node_modules\@craco\craco\lib\features\plugins.js:64:29
    at Array.forEach (<anonymous>)
    at applyWebpackConfigPlugins (D:\Administration\administration-ui\node_modules\@craco\craco\lib\features\plugins.js:63:29)
    at mergeWebpackConfig (D:\Administration\administration-ui\node_modules\@craco\craco\lib\features\webpack\merge-webpack-config.js:110:30)
    at overrideWebpackDev (D:\Administration\administration-ui\node_modules\@craco\craco\lib\features\webpack\override.js:11:36)
error Command failed with exit code 1.
```

**Comment by oklas** [comment]
Hi @AVAVT, check content of `./jsconfig.paths.json` (check `compilerOptions.paths`), it must be exactly as [described](https://github.com/oklas/react-app-rewire-alias#enumerate-aliases-in-jsconfigpathsjson-or-tsconfigpathsjson):

```js
// jsconfig.paths.json or tsconfig.paths.json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "example/*": ["example/src/*"],
      "@library/*": ["library/src/*"]
    }
  }
}
```

**Comment by AVAVT** [comment]
Hey @oklas , it doesn't seems to be the issue.

I suspected the lib doesn't work on js, so switched to typescript and just by copying everything over replacing `js` -> `ts` it works perfectly.

**Comment by oklas** [comment]
@AVAVT, I do not get which files you copied and replaced. You did not write that issue is solved but that you not sure. So could you provide more info about is anything else to check or help or fix from my side?

**Comment by AVAVT** [comment]
@oklas Hi, so I will describe my situation in steps:

1. I create a CRA app (the `npx create-react-app my-app` thing). Adding `craco` and `react-app-rewire-alias`. With the following configs:

`jsconfig.paths.json`:

```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "GameConfigs/*": ["../GameConfigs/*"]
    }
  }
}
```

`craco.config.js`

```
const {
  CracoAliasPlugin,
  configPaths,
} = require("react-app-rewire-alias/lib/aliasDangerous");

const aliasMap = configPaths("./jsconfig.paths.json");

module.exports = {
  plugins: [
    {
      plugin: CracoAliasPlugin,
      options: { alias: aliasMap },
    },
  ],
  style: {
    postcss: {
      plugins: [require("tailwindcss"), require("autoprefixer")],
    },
  },
};
```

`jsconfig.json`

```
{
  "extends": "./jsconfig.paths.json",
  "compilerOptions": {
  }
}
```

The above configs give me the errors I mentioned in previous comment.

============

After trying many things to no avail. I remember a situation I had before where the libs don't work in js CRA but works with ts CRA, so I create another CRA app with typescript template (the `npx create-react-app my-app --template typescript` thing)

After that I use the exact same 3 files above, changing all `js` into `ts`.

And it worked.

**Comment by oklas** [comment]
The report from @AVAVT moved to #41. Thanks 🙏
