### ISSUE TITLE
Invalid ForkTsCheckerWebpackPlugin configuration object

### ISSUE THREAD

**Issue by hirikarate** [oklas/react-app-rewire-alias#44]
I'm using
- "react-scripts": "5.0.0"
- "react-app-rewire-alias": "1.1.5",
- "react-app-rewired": "2.1.8"

and encountering this error:

```
Invalid configuration object. ForkTsCheckerWebpackPlugin has been initialized using a configuration object that does not match the API schema.
 - configuration has an unknown property 'compilerOptions'. These properties are valid:
   object { async?, typescript?, eslint?, formatter?, issue?, logger? }
```

I believe the problem is at [aliasDangerous.js#L98](https://github.com/oklas/react-app-rewire-alias/blob/master/src/aliasDangerous.js#L98) where the invalid property `compilerOptions` is added.
```javascript
const options = {...opts, compilerOptions}
```

I tried modifying the source code locally and this version works:
```javascript
const options = {
   ...opts,
   typescript: {
      ...opts.typescript,
      configOverwrite: compilerOptions,
   }
}
```

If you think this fix is reasonable, please apply it.

**Comment by oklas** [comment]
This is released 1.1.6, you can check

**Comment by omerts** [comment]
@oklas I am still having issues with this:
TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received an instance of Object
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Module.require (node:internal/modules/cjs/loader:998:3)
    at require (node:internal/modules/cjs/helpers:102:18)
    at ForkTsCheckerWebpackPlugin.validateTypeScript (/Users/NothingButOne/develop/GophOR/packages/gophor-web/node_modules/fork-ts-checker-webpack-plugin/lib/index.js:141:20)
    at new ForkTsCheckerWebpackPlugin (/Users/NothingButOne/develop/GophOR/packages/gophor-web/node_modules/fork-ts-checker-webpack-plugin/lib/index.js:93:19)
    at expandPluginsTsChecker (/Users/NothingButOne/develop/GophOR/packages/gophor-web/node_modules/react-app-rewire-alias/src/aliasDangerous.js:105:26)

**Comment by oklas** [comment]
Previous implementation has been added for compatibility.
